name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - master
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing Dependencies
        run: yarn
      - name: Running Unit Tests
        run: yarn run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing Dependencies
        run: yarn
      - name: Building App
        run: yarn run build
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Deploying to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_SECRET }}"
