name: Build on PR
"on": pull_request
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing Dependencies
        run: yarn
      - name: Running Unit Tests
        run: yarn run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing Dependencies
        run: yarn
      - name: Building App
        run: yarn run build
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn run build
          start: yarn start
          wait-on: http://localhost:3000

  # cypress-run:
  #   runs-on: ubuntu-latest
  #   container: cypress/browsers:node12.18.3-chrome87-ff82
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         # Specify Browser since container image is compile with Firefox
  #         browser: chrome
