name: Build on PR
"on": pull_request
jobs:
  unit_test:
    runs-on: ubuntu-latest
    env:
      TEST_LLAMA_NODES_ID: ${{ secrets.LLAMA_NODES_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing Dependencies
        run: yarn
      - name: Running Unit Tests
        run: yarn run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing Dependencies
        run: yarn
      - name: Building App
        run: yarn run build
  preview_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing Dependencies
        run: yarn
      - name: Building App
        run: yarn run build
      - name: Deploy to Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: backd-ffbef
