name: Build on PR
"on": pull_request
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn && yarn run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: Installing Client Dependencies
        run: yarn
      - name: Building
        run: yarn run build
