name: Build on PR
"on": pull_request
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn && yarn run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing Client Dependencies
        run: yarn
      - name: Building
        run: yarn run build
